<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.414.1" />
    <PackageReference Include="ClosedXML.Report" Version="0.2.10" />
    <PackageReference Include="CloudinaryDotNet" Version="1.27.2" />
    <PackageReference Include="Confluent.Kafka" Version="2.8.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.17.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="IdentityModel" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Features" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.3.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.3.1" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Version="8.0.12" />
    <PackageReference Include="MimeKit" Version="4.9.0" />
    <PackageReference Include="Sieve" Version="2.5.5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.1" />
    <PackageReference Include="Twilio" Version="7.8.3" />
    <PackageReference Include="VNPAY.NET" Version="8.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\api_be.Core.csproj" />
    <ProjectReference Include="..\Domain\api_be.Domain.csproj" />
  </ItemGroup>

</Project>
