version: '3.8'

services:
  # SQL Server
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sqlserver
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=101204
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql
  #   networks:
  #     - backend

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # Zookeeper (Required for Kafka)
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   container_name: zookeeper
  #   restart: unless-stopped
  #   networks:
  #     - backend
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # Kafka UI (Optional - Web UI for Kafka)
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   restart: unless-stopped
  #   networks:
  #     - backend
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:29092

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  # Kibana (Optional - Web UI for Elasticsearch)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
  # # SignalR Hub (Mock service)
  # signalr-hub:
  #   image: mcr.microsoft.com/dotnet/aspnet:6.0
  #   container_name: signalr-hub
  #   build:
  #     context: ./SignalRApp  # Your SignalR app folder (must contain Dockerfile)
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - backend
  #   depends_on:
  #     - redis

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
  elasticsearch_data:
    driver: local
  mongodb_data:
    driver: local

#docker-compose down -v || stop
#docker-compose up --build
# docker exec -it kibana curl -I http://localhost:5601
